theme = "hyde"
baseURL = "https://haowu.netlify.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
enableEmoji = true
googleAnalytics = "UA-105636148-1"

title = "Hao"

[params]
  disqusShortname = "haowu"
  description = "Welcome to my website."

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "CV"
  url = "/vitae/"
  weight = 3
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/mohowu"
  weight = 4
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/WuMoho"
  weight = 5


  
