DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://moho.netlify.com/"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-105636148-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "ananke"
title = "Moho"
[Taxonomies]
category = "categories"
series = "series"
series-desc = "series-desc"
tag = "tags"
[params]
background_color_class = "bg-black"
description = ""
disqusShortname = "haowu"
facebook = ""
favicon = "/image/favicon.ico"
featured_image = "/image/ist_pano.JPG"
github = "https://github.com/mohowu"
instagram = "https://www.instagram.com/moho_wu/"
linkedin = ""
mainImage = "/image/moho4.png"
pygmentsUseClassic = true
recent_posts_number = 2
twitter = "https://twitter.com/WuMoho"
youtube = ""
[permalinks]
post = "/:year/:month/:day/:slug/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
