theme = "hyde"
baseURL = "https://haowu.netlify.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
enableEmoji = true
googleAnalytics = "UA-105636148-1"

title = "Hao"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  disqusShortname = "haowu"
  description = ""
  twitter = "https://twitter.com/WuMoho"
  github = "https://github.com/mohowu"
  copyright = "Powered by [Hugo](http://gohugo.io) <br/> &copy; 2017 [Hao Wu](https://haowu.netlify.com). All rights reserved."
  mainImage = "/image/moho4.png"
  

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"
	category = "categories"

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "CV"
  url = "/vitae/"
  weight = 3
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 4
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5


  
