---
title: "Curriculum Vitae - Hao Wu"
bibliography: ../static/bib/vitae.bib
csl: ../static/bib/elsevier-harvard-with-url.csl
nocite: |
  @wu2017, @kenagy2016, @wu2015, @steinle2015, @lin2017
disableComments: true
hideDate: true
---

### Education 

* __Ph.D.__   Urban air quality and human exposure assessment ([*Thesis*](../pdf/PhDThesis_HW_final.pdf)), University of Edinburgh, UK
* __BSc (Hons)__     Environmental and Sustainable Chemistry (1^st^ Class), Unversity of Edinburgh, UK
* __BSc__     Applied Chemistry, South China University of Technology, China

### Employment 

* __2017 -- Present__: _Data Science Specialist_, Ricardo Energy & Environment

> In this role I primarily work on air quality data, which includes but not limited to dynamic reporting, data visualisation and building tools for analysing data in more efficient and reproducible way. This is achieved by utilising many powerful R packages such as Rmarkdown, Shiny and ggplot2. Bespoke R packages are built to simplify the process of data analysis and visualisation.

* __2013 -- 2017__: _PhD Student_, University of Edinburgh

> My PhD research focuses on integrating measurements and modelling of urban air pollution to improve human exposure assessment. The measurements are taken both in mobile fashion and at fixed locations. Analysis of air quality data incorporates the spatial elements of the mobile measurements and the long-term trends from fixed-site measurements. Evaluation of the portable monitors against reference analysers was also a key part of my research. Modelling of the traffic related air pollutants such as NO~2~ and ultrafine particles uses dispersion and statistical models with the aim to provide basis for more spatially resolved exposure assessment.


### Technical Skills

__Programming Language__

* Advanced: R 
* Intermediate: Markdown
* Basic: CSS, HTML, SQL

__Software__

* Adcanced: RStudio, ADMS-Urban, MS Word
* Intermediate: ArcGIS, FME, MS Excel 


### Conferences and Training Courses

* 2016: Oral presentation at International Society of Exposure Science at Amsterdam, Netherland
* 2016: Oral presentation at Annual UK Review Meeting on Outdoor and Indoor Air Pollution Research at Solihull, UK
* 2015: Poster presentations at Annual UK Review Meeting on Outdoor and Indoor Air Pollution Research at Solihull, UK
* 2015: FME Desktop Introductory and Advanced Training at Centre for Ecology and Hydrology (CEH), UK
* 2014: Poster presentations at Annual UK Review Meeting on Outdoor and Indoor Air Pollution Research at Solihull, UK
* 2014: ACCENT Plus Summer School on Drivers, Feedbacks and Impacts in Air Quality and Climate Change at the University of Urbino, Italy.
* 2014: Trainings on ADMS-Urban and EMIT software at Cambridge Environmental Research Consultants (CERC), UK.

### Teaching Experience

* 2013 -- 2016: 2^nd^ Year Physical Chemistry Lab Demonstrator
* 2013 -- 2016: 2^nd^ Year Environmental Chemistry Lab Demonstrator


### Honours and Awards

* 2016: Reviewer of Environmental Pollution Journal
* 2013 -- 2016: Edinburgh Global Research Scholarship
* 2013: Undergraduate Research Project Prize

### Publications

